### ISSUE TITLE
Authorize guests to rooms once a logged in user is present

### ISSUE THREAD

**Issue by cs35-owncloud** [miroslavpejic85/mirotalksfu#141]
Hello,

first thing first, happy new year and thank you for this tool, I'm quite amazed with it, it really features everything we wished and works out of the box quite easily. Good job !

Maybe my issue is more of a question rather than a feature if I misunderstood how the host protection works, sorry if this subject is already covered, feel free to give me pointers to RTFM :)

# Feature request

I'd like to have the ability that once a user listed in **host.users** is logged in on a room, any other users can reach the room without any authentication. It's mostly to have a conference with customers, to create an account for every customer is not feasible.

As of now, when you edit **app/src/config.js**, you can set **protected** and **user_auth** to true/false.
If **protected** is set to true you have to login to first reach the app.
If **user_auth** is set to true, you have to login to reach a room.
I thought I read somewhere that guests could join a room once a user was already logged in, but I can't find this information again (I'll search again).

## Pros

So the main goal of this feature request would be to directly reach a specific room without any login as long as a user is already logged in. Maybe it could be a new variable **allow_guest** that once set to true would allow guest to reach a room only when a specific user is already logged in.

Thanks.

EDIT:

Found the explanation about the [guest joining](https://github.com/miroslavpejic85/mirotalksfu/commit/11790210a202e4e238df9e0cbf0a73a0cdf314d9#commitcomment-66409924) but it doesn't seem to be working.

**Comment by singhkaram** [comment]
You can use the token when creating a room once created convert it to a public API for that u will need to create a convert to public API. It might solve your issue

**Comment by cs35-owncloud** [comment]
That doesn't really seem like what was explained in the [guest process](https://github.com/miroslavpejic85/mirotalksfu/commit/11790210a202e4e238df9e0cbf0a73a0cdf314d9#commitcomment-66409924). It would be easier for guest to just join a room as described : /

**Comment by miroslavpejic85** [comment]
Hello @cs35-owncloud 

I'm excited to inform you that the security feature you've been looking for is already available in Mirotalk SFU. You can achieve this by following the steps outlined in [this commit](https://github.com/miroslavpejic85/mirotalksfu/commit/ab21686e9ad4b75e14c3ee020141d61b33111dde#commitcomment-62398736). (Check the updates)

To implement this enhancement, update your `config.js` file with the following settings:

```js
//....
host: {
    protected: true,
    user_auth: false,
    users: [
        {
            username: 'YOUR-USERNAME',
            password: 'YOUR-PASSWORD',
        }
        //...
    ],
},
//...
```

With these configurations, the host will have exclusive access to the room. Once the host leaves, guests won't be able to rejoin unless they provide a valid username and password defined in the `users` section.

For any questions or clarifications, feel free to join our vibrant [forum community](https://discord.gg/rgGYfeYW3N). Our community members are ready to assist you, and you can find answers without the need to open issues on GitHub.

Wishing you a fantastic 2024!

Best regards,
Miroslav

**Comment by cs35-owncloud** [comment]
Hello @miroslavpejic85 and thanks for your fast answer !
I actually did this configuration, but even though I'm already logged in and I've created a specific room, guests cannot reach that specific room, the app is asking them to log in. Is it clearer ?
My configuration is as follow:

```
    host: {
        /*
            Host Protection (default: false)
            To enhance host security, enable host protection - user auth and provide valid
            usernames and passwords in the users array.
        */
        protected: true,
        user_auth: false,
        users: [
            {
                username: 'account1',
                password: 'xxxx',
            }
            //...
        ],
```

Thanks.

**Comment by cs35-owncloud** [comment]
OK I think I finally understood, my mistake, it's working the opposite way as I understood/wished it to be.
Actually guests have to reach a room first, then once the host is logged in, it's locking the room and no one can join anymore.
It's not really practical with real customers as they could reach the room once the host is already logged in.
It would be easier for guests to be in a lobby as long as the host is not logged in and once the host is logged in, guests are added to the room and anyone could join. The host could set a password to the room to locked it.

**Comment by cs35-owncloud** [comment]
Well sorry @miroslavpejic85 but after several tries (guess I had some caching issues), the host login is not working with guest access, it's easy to replicate.
Set the configuration as follow:

```
    host: {
        /*
            Host Protection (default: false)
            To enhance host security, enable host protection - user auth and provide valid
            usernames and passwords in the users array.
        */
        protected: true,
        user_auth: false,
        users: [
            {
                username: 'account1',
                password: 'xxxx',
            }
            //...
        ],
```

With one browser go to a room, log in, with an other browser (or private navigation), also go to the room.
You will never reach the room as a guest.
I tried the other way too, to go to the room first with the guest and log in with the other browser.
It's always asking for username/password and the guest can never enter the room.

**Comment by miroslavpejic85** [comment]
Hey @cs35-owncloud,

We [tested](https://www.dropbox.com/scl/fi/fw78geg5ba7wh0g1mebx1/host-protected.mp4?rlkey=l8svwpj1yhi6m9awh5zsfivxp&dl=0) and works as expected.

If `host.protected: true`:

1. Guests are unable to join the room until the host completes authentication, they will be redirected to the login page.
2. The host gains access by logging in with the designated username and password.
3. Following successful authentication by the host, guests are then permitted to join the room.


> \[!NOTE]
>
> 1. To apply the configuration changes, it is imperative to restart your MiroTalk SFU instance.
> 2. Ensure that you are using the latest `version 1.3.50` to take advantage of all features and enhancements.
> 3. Clear also your browser cache.

Thank you for testing, and we appreciate your commitment to a secure and seamless experience with MiroTalk SFU.

Best regards,
Miroslav

**Comment by cs35-owncloud** [comment]
Thanks for your answer and sorry to bother you.
I think I have the idea of why it doesn't work.
I'm installing it with Docker, and I think that the version in the dockerhub is not 1.3.50, but 1.3.49:

Here's my docker-compose.yml:

```
version: '3'

services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            # These volumes are not mandatory, comment if you want to use it
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
 ```

And the docker log of mirotalksfu when starting

```
[2024-01-03 14:51:17.870] [Server] Settings {
  app_version: '1.3.49',
  node_version: '18.19.0',
  hostConfig: {
    protected: true,
    user_auth: false,
    users: [
      { username: 'username', password: 'password' },
      { username: 'username2', password: 'password2' }
    ],
    authenticated: false
```

**Comment by miroslavpejic85** [comment]
```bash
docker-compose down
```

Edit your `docker-compose.yml` as the following:

```yml
version: '3'

services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
             - ./app/:/src/app/:ro
             - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
```

```bash
docker-compose up 
```
