### ISSUE TITLE
docker-compose.yml template is confusing

### ISSUE THREAD

**Issue by nazar-pc** [miroslavpejic85/mirotalksfu#186]
### Describe the bug

It is helpful that template is provided, but the fact that it has both `image` and `build` keys doesn't really make sense.
Also I'm not sure why `container_name` and `hostname` are really needed there, I would minimize the template to the bare minimum.
And lastly as you're editing it, `version` should be removed as it is deprecated in current versions of Docker Compose.

### Steps to reproduce

-

### Expected behavior

-

### Device

- [ ] Android
- [ ] iPhone
- [ ] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

**Comment by miroslavpejic85** [comment]
Hi nazar-pc,

Thank you for your feedback! I completely agree that the inclusion of both the image and build keys may not be necessary, and the container_name and hostname could be minimized for simplicity. I also appreciate your point about removing the version as it's deprecated in current Docker Compose versions. 

Originally, I was building images outside of GitHub, and pushing them to Docker Hub. Now, the entire process is automated through GitHub Actions using the [ci.yml](https://github.com/miroslavpejic85/mirotalksfu/blob/main/.github/workflows/ci.yml) workflow.

Would you mind submitting a pull request with the proposed changes? It would be greatly appreciated. Thanks again for your input and support!

**Comment by miroslavpejic85** [comment]
Hi nazar-pc,

Thank you for your feedback! I completely agree that the inclusion of both the image and build keys may not be necessary. I also appreciate your point about removing the version as it's deprecated in current Docker Compose versions.  

Regarding `container_name`, we want to keep it for the following reasons:

1. **Easier Access**: A fixed `container_name` simplifies interactions with the container, making commands like `docker exec` or `docker logs` more predictable and easier to use for troubleshooting.

2. **Improved Readability**: It provides a clear, human-readable name, which is particularly useful for managing multiple containers and collaborating with others.

3. **Networking Convenience**: A consistent `container_name` ensures easy communication between containers, especially in multi-container setups where containers need to refer to each other by name.

4. **Consistency Across Environments**: Defining the `container_name` guarantees that the container has the same name in all environments (development, staging, production), which helps ensure consistency.

5. **Script Integration**: Fixed names make it easier to automate deployment or integrate with other tools, reducing the need for dynamic name resolution.

Regarding the `hostname` I think generally, consistency between `container_name` and `hostname` is good practice.

> \[!NOTE]
>
> Originally, I was building images outside of GitHub, and pushing them to Docker Hub. Now, the entire process is automated through GitHub Actions using the [ci.yml](https://github.com/miroslavpejic85/mirotalksfu/blob/main/.github/workflows/ci.yml) workflow.

Would you mind submitting a pull request with the proposed changes? It would be greatly appreciated. Thanks again for your input and support!

**Comment by miroslavpejic85** [comment]
**PS:** We could include the `build` section as a commented-out option in the Docker Compose file. This approach would be helpful for users who might want to build the image themselves. The final `docker-compose.template.yml` file could look like this:

```yaml
services:
    mirotalksfu:
        # Use the pre-built image from Docker Hub (default option)
        image: mirotalk/sfu:latest
        # Uncomment the following lines to build the image locally instead
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            # Mandatory volume if `server.recording.enabled` is true in app/src/config.js
            # - ./app/rec:/src/app/rec
            # Mandatory volume if `server.rtmp.enabled.fromFile` is true in app/src/config.js
            # - ./app/rtmp:/src/app/rtmp
            # Optional volumes for real-time updates during development:
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
```

When preparing the file for production, users can simplify it by removing or commenting out unnecessary parts. For example, the production-ready `docker-compose.yml` might look like this:

```yaml
services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        restart: unless-stopped
        container_name: mirotalksfu
        hostname: mirotalksfu
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
```

---

**Regarding the `version` field:**

It’s a good idea to include the `version` field in the template file for backward compatibility. If the `version` field is missing and the `docker-compose.yml` file is used with an older version of Docker Compose (prior to 1.27.0), Docker Compose will assume the legacy Compose format. This can lead to **unexpected behavior**, as certain features and syntax are only available in specific Compose file versions.

For maximum compatibility, the `docker-compose.template.yml` file could include a version line like this:

```yaml
version: '3.9' # Ensures compatibility with modern Docker Compose features
services:
    mirotalksfu:
        ...
```

---

**Summary of Changes:**
1. Comment out the `build` section to provide users with the option to build locally if needed:
   ```yaml
        # Uncomment the following lines to build the image locally instead
        # build:
        #     context: .
        #     dockerfile: Dockerfile
   ```

2. Include the `version` field to ensure backward compatibility, especially for older versions of Docker Compose.

By structuring the file this way, we provide flexibility and clarity for both development and production environments. What do you think?

**Comment by nazar-pc** [comment]
> PS: We could include the build section as a commented-out option in the Docker Compose file. This approach would be helpful for users who might want to build the image themselves.

Not sure how helpful that is, you can build it with `docker build -t mirotalk .` explicitly, which isn't that difficult.

> It’s a good idea to include the version field in the template file for backward compatibility. If the version field is missing and the docker-compose.yml file is used with an older version of Docker Compose (prior to 1.27.0), Docker Compose will assume the legacy Compose format.

Docker Compose 1.27.0 was released in 2020, more than 4 years ago! I'm not sure it is good to encourage people to not upgrade software for 4+ years with countless security issues discovered since. If someone does run ancient version and is not willing to upgrade they might as well specify the version themselves. Certainly not worth the warning for those who do upgrade in time.

**Comment by miroslavpejic85** [comment]
> Not sure how helpful that is, you can build it with docker build -t mirotalk . explicitly, which isn't that difficult.

You're right. We'll remove that step.

> Docker Compose 1.27.0 was released in 2020, more than 4 years ago! I'm not sure it is good to encourage people to not upgrade software for 4+ years with countless security issues discovered since. If someone does run ancient version and is not willing to upgrade they might as well specify the version themselves. Certainly not worth the warning for those who do upgrade in time.

I agree. We'll remove the version requirement entirely.

**Final `docker-compose.template.yml`:**

```yml
services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
            - ./app/src/config.js:/src/app/src/config.js:ro
            # Mandatory volume if `server.recording.enabled` is true in app/src/config.js
            # - ./app/rec:/src/app/rec
            # Mandatory volume if `server.rtmp.enabled.fromFile` is true in app/src/config.js
            # - ./app/rtmp:/src/app/rtmp
            # Optional volumes for real-time updates:
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
```

We’d love to have you as a contributor! If you'd like, feel free to send us a PR with these changes? 
Thanks for your help!
